# Generated by Django 4.0.6 on 2022-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_workstream_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='all_time_contributors',
            field=models.JSONField(default=dict),
        ),
    ]
