# Generated by Django 4.0.6 on 2022-07-23 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('budget_link', models.URLField(max_length=400)),
                ('current_gtc_num', models.URLField(max_length=400)),
                ('current_gtc_graph', models.URLField(max_length=400)),
                ('current_stable_num', models.URLField(max_length=400)),
                ('current_stable_graph', models.URLField(max_length=400)),
                ('all_time_contributors', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Steward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('steward_since', models.DateTimeField(auto_now=True)),
                ('statement_post', models.URLField(max_length=400)),
                ('gitcoin_username', models.CharField(max_length=60, unique=True)),
                ('discourse_username', models.CharField(max_length=60, unique=True)),
                ('profile_image', models.URLField(blank=True, max_length=400, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workstream')),
            ],
        ),
    ]
