# Generated by Django 4.0.6 on 2022-08-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stats_alter_workstream_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='gtc_balance',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='gtc_graph',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stable_coin_balance',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stable_graph',
            field=models.JSONField(null=True),
        ),
    ]
