# Generated by Django 4.0.6 on 2022-08-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_stats_gtc_balance_alter_stats_gtc_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstream',
            name='stats',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.stats'),
        ),
    ]
